from __future__ import annotations

import html
from pathlib import Path
import streamlit as st

AGENT_META = {
    "orchestrator": ("✦", "ROG AI Core", "Orquestração inteligente e delegação automática"),
    "personal": ("◎", "Pessoal", "Rotina, decisões e organização"),
    "finance": ("◈", "Finanças", "Planejamento e análise financeira"),
    "tech": ("⌘", "Tecnologia", "Código, hardware e sistemas"),
    "coach": ("△", "Coach", "Treino, performance e hábitos"),
    "business": ("◇", "Negócios", "Projetos, estratégia e receita"),
    "english": ("A", "English", "Conversação, escrita e fluência"),
    "document": ("▤", "Documentos", "Arquivos, OCR e RAG"),
}
PROFILE_LABELS = {"allan": "Allan", "beatriz": "Beatriz", "natan": "Natan", "tainan": "Tainan"}
MARK_SVG = '<svg viewBox="0 0 64 64" aria-hidden="true"><defs><linearGradient id="rogMark" x1="8" y1="8" x2="56" y2="56" gradientUnits="userSpaceOnUse"><stop stop-color="#C4B5FD"/><stop offset=".48" stop-color="#8B5CF6"/><stop offset="1" stop-color="#22D3EE"/></linearGradient></defs><path fill="#0E1020" stroke="#6D5BD0" stroke-width="2" d="M32 3 57 17v30L32 61 7 47V17z"/><path fill="url(#rogMark)" d="m18 40 7-21h17l6 7-7 7 7 12H37l-6-11-3 11H16l8-7h14l-3-6H24l-3 8z"/><circle cx="46" cy="18" r="3" fill="#67E8F9"/></svg>'


def inject_design_system() -> None:
    st.markdown(r'''<style>
:root{color-scheme:dark;--rog-bg:#030407;--rog-surface:#090b11;--rog-surface2:#0f121b;--rog-line:rgba(255,255,255,.09);--rog-text:#f7f7fb;--rog-muted:#9298a8;--rog-dim:#686f80;--rog-accent:#8a68ff;--rog-accent2:#b29cff;--rog-success:#51ddb2}
html,body,.stApp,[data-testid="stAppViewContainer"]{background:radial-gradient(900px 420px at 65% -180px,rgba(124,87,255,.18),transparent 72%),var(--rog-bg)!important;color:var(--rog-text)!important}body{font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif!important}#MainMenu,footer,.stDeployButton,[data-testid="stToolbar"]{display:none!important}[data-testid="stHeader"]{height:0!important;background:transparent!important}[data-testid="stSidebarCollapsed"],[data-testid="stSidebarCollapsedControl"],[data-testid="stSidebarCollapseButton"]{visibility:visible!important;opacity:1!important;z-index:10000!important;pointer-events:auto!important}[data-testid="stSidebarCollapsed"]{display:block!important;position:fixed!important;top:10px!important;left:10px!important}[data-testid="stSidebarCollapsed"] button,[data-testid="stSidebarCollapsedControl"] button,[data-testid="stSidebarCollapseButton"] button,[data-testid="stSidebarCollapseButton"]{display:flex!important;background:#11141d!important;border:1px solid rgba(178,156,255,.45)!important;border-radius:11px!important;color:#fff!important;box-shadow:0 8px 28px rgba(0,0,0,.55)!important;min-width:42px!important;min-height:42px!important}[data-testid="stAppViewBlockContainer"]{padding-top:0!important}.block-container{max-width:1280px!important;padding:14px clamp(18px,3vw,42px) 132px!important}a{color:var(--rog-accent2)!important}*:focus-visible{outline:2px solid var(--rog-accent2)!important;outline-offset:2px!important}
[data-testid="stSidebar"]{background:linear-gradient(180deg,#090b10,#050609)!important;border-right:1px solid var(--rog-line)!important;min-width:286px!important}[data-testid="stSidebar"]>div:first-child{padding:18px 13px 22px!important}[data-testid="stSidebar"] button{width:100%!important;min-height:43px!important;justify-content:flex-start!important;border-radius:12px!important;border:1px solid transparent!important;background:transparent!important;color:#b7bdcb!important;font-size:12px!important;font-weight:550!important;transition:background .16s ease,border-color .16s ease,color .16s ease,transform .16s ease!important}[data-testid="stSidebar"] button:hover{background:rgba(255,255,255,.055)!important;border-color:var(--rog-line)!important;color:white!important}[data-testid="stSidebar"] button:active{transform:scale(.985)}[data-testid="stSidebar"] button[kind="primary"]{background:linear-gradient(90deg,rgba(126,91,255,.20),rgba(126,91,255,.07))!important;border-color:rgba(142,108,255,.34)!important;color:#faf8ff!important;box-shadow:inset 3px 0 0 var(--rog-accent)!important}[data-testid="stSidebar"] hr{border-color:var(--rog-line)!important;margin:15px 4px!important}
.rog-brand{display:flex;align-items:center;gap:12px;padding:3px 4px 18px}.rog-logo{width:42px;height:42px;display:block;filter:drop-shadow(0 10px 18px rgba(118,83,255,.28))}.rog-brand-title{font-weight:880;font-size:16px}.rog-brand-sub{font-size:8px;color:var(--rog-muted);letter-spacing:1.2px;margin-top:3px}.rog-profile{padding:11px 12px;border-radius:13px;border:1px solid var(--rog-line);background:rgba(255,255,255,.027);margin:0 2px 18px}.rog-profile-line{display:flex;align-items:center;gap:9px}.rog-avatar{width:27px;height:27px;border-radius:9px;display:grid;place-items:center;background:rgba(138,104,255,.16);color:#d8ceff;font-size:11px;font-weight:800}.rog-profile strong{font-size:11px}.rog-profile span{display:block;color:var(--rog-success);font-size:8px;margin-top:2px}.rog-section{color:#737b8e;font-size:8px;text-transform:uppercase;letter-spacing:1.35px;font-weight:850;margin:15px 7px 8px}
.st-key-rog_top_nav{position:sticky;top:8px;z-index:100;background:rgba(6,7,12,.91);border:1px solid var(--rog-line);border-radius:17px;padding:8px 10px;margin:0 0 16px;box-shadow:0 14px 42px rgba(0,0,0,.28);backdrop-filter:blur(18px)}.st-key-rog_top_nav [data-testid="stHorizontalBlock"]{align-items:center}.rog-top-brand{display:flex;align-items:center;gap:9px}.rog-top-brand img{width:32px;height:32px}.rog-top-brand strong{font-size:12px}.rog-top-brand span{display:block;color:var(--rog-muted);font-size:8px;margin-top:1px}.rog-top-context{text-align:center;color:var(--rog-muted);font-size:9px}.rog-top-context strong{display:block;color:var(--rog-text);font-size:12px;margin-bottom:2px}
.rog-hero{position:sticky;top:0;z-index:5;padding:5px 0 18px;margin-bottom:22px;border-bottom:1px solid var(--rog-line);background:linear-gradient(180deg,var(--rog-bg) 80%,transparent)}.rog-hero-row{display:flex;align-items:center;gap:13px}.rog-agent-icon{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;background:linear-gradient(145deg,rgba(133,98,255,.22),rgba(133,98,255,.08));border:1px solid rgba(145,112,255,.32);color:#d0c3ff;font-size:16px;font-weight:850}.rog-agent-name{font-size:15px;font-weight:820}.rog-agent-desc{color:var(--rog-muted);font-size:10px;margin-top:3px}.rog-status{margin-left:auto;display:flex;align-items:center;gap:6px;color:#b6f5e2;font-size:9px;padding:6px 10px;border:1px solid rgba(81,221,178,.18);background:rgba(81,221,178,.06);border-radius:999px}.rog-status-dot{width:6px;height:6px;border-radius:50%;background:var(--rog-success)}.rog-status.is-busy{color:#ddd2ff;border-color:rgba(138,104,255,.25);background:rgba(138,104,255,.09)}.rog-status.is-busy .rog-status-dot{background:var(--rog-accent2);animation:rog-pulse 1.1s infinite}@keyframes rog-pulse{50%{opacity:.35}}
.rog-welcome-copy{display:flex;min-height:300px;flex-direction:column;justify-content:center;padding:28px 10px}.rog-eyebrow{font-size:9px;color:#a995ff;text-transform:uppercase;letter-spacing:1.6px;font-weight:800;margin-bottom:11px}.rog-welcome-copy h2{margin:0;font-size:clamp(30px,4vw,48px);letter-spacing:-1.8px;line-height:1.04}.rog-welcome-copy p{color:var(--rog-muted);max-width:540px;font-size:13px;line-height:1.7;margin:16px 0 0}.rog-welcome-art{position:relative;display:grid;place-items:center;min-height:300px;border-radius:26px;overflow:hidden;background:radial-gradient(circle at 50% 48%,rgba(92,62,220,.18),transparent 58%);border:1px solid rgba(255,255,255,.055)}.rog-welcome-art img{width:min(92%,360px);filter:drop-shadow(0 28px 38px rgba(32,16,89,.42))}
[data-testid="stChatMessage"]{max-width:880px;margin:0 auto 12px!important;padding:0!important;background:transparent!important;gap:10px!important}[data-testid="stChatMessageContent"]{border:1px solid var(--rog-line);border-radius:16px;padding:13px 16px!important;background:rgba(15,18,27,.82);font-size:14px;line-height:1.68;overflow-wrap:anywhere}[data-testid="stChatMessage"]:has([data-testid="stChatMessageAvatarUser"]) [data-testid="stChatMessageContent"]{background:linear-gradient(145deg,rgba(109,76,224,.24),rgba(61,43,126,.2));border-color:rgba(140,105,255,.25)}[data-testid="stChatMessageContent"] p:last-child{margin-bottom:0}
[data-testid="stChatInput"]{border-radius:18px!important;border:1px solid rgba(148,118,255,.35)!important;background:rgba(13,16,24,.98)!important;box-shadow:0 16px 56px rgba(0,0,0,.48)!important;min-height:58px!important}[data-testid="stChatInput"]:focus-within{border-color:var(--rog-accent2)!important;box-shadow:0 16px 56px rgba(0,0,0,.5),0 0 0 3px rgba(138,104,255,.12)!important}[data-testid="stBottom"]{background:linear-gradient(180deg,transparent,var(--rog-bg) 28%)!important;padding-top:28px!important}[data-testid="stChatInput"] button{color:#c7b9ff!important}
[data-testid="stAlert"],[data-testid="stVerticalBlockBorderWrapper"]>div{border-radius:16px!important;border-color:var(--rog-line)!important}.stButton>button{border-radius:12px!important;transition:transform .13s ease,border-color .13s ease!important}.stButton>button[kind="primary"],button[kind="primaryFormSubmit"]{background:linear-gradient(135deg,#6848ec,#9272ff)!important;border-color:#9d83ff!important;color:#fff!important}.stButton>button:hover{border-color:rgba(145,112,255,.5)!important}.stButton>button:active{transform:scale(.985)}.stButton>button:disabled{opacity:.48!important;cursor:not-allowed!important}.rog-quick-label{text-align:center;color:var(--rog-dim);font-size:9px;text-transform:uppercase;letter-spacing:1.1px;margin:2px 0 -3px}
@media(max-width:760px){.block-container{padding:8px 10px 116px!important}.st-key-rog_top_nav{top:6px;margin-bottom:10px;padding:6px}.rog-top-brand span,.rog-top-context{display:none}.rog-hero{padding-top:3px;margin-bottom:14px}.rog-agent-desc{max-width:47vw;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rog-status{padding:5px 7px}.rog-status span:last-child{display:none}.rog-welcome-copy{min-height:auto;text-align:center;padding:18px 8px 8px}.rog-welcome-copy p{font-size:12px;margin:11px auto 0}.rog-welcome-art{min-height:190px}.rog-welcome-art img{width:min(74vw,250px)}[data-testid="stSidebar"]{width:min(88vw,310px)!important}[data-testid="stChatMessageContent"]{padding:11px 13px!important;font-size:13px}.rog-quick-label{margin-top:8px}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
.rog-logo svg{width:42px;height:42px;display:block}.st-key-rog_welcome_art{position:relative;display:grid;place-items:center;min-height:300px;border-radius:26px;overflow:hidden;background:radial-gradient(circle at 50% 48%,rgba(92,62,220,.18),transparent 58%);border:1px solid rgba(255,255,255,.055)}.st-key-rog_welcome_art [data-testid="stFullScreenFrame"],.st-key-rog_welcome_art [data-testid="stFullScreenFrame"]>div{width:100%!important;display:grid!important;place-items:center!important}.st-key-rog_welcome_art img{width:min(92%,360px)!important;height:auto!important;filter:drop-shadow(0 28px 38px rgba(32,16,89,.42))}@media(max-width:760px){.st-key-rog_welcome_art{min-height:190px}.st-key-rog_welcome_art img{width:min(74vw,250px)!important}}
/* Fluid chat shell — intentionally last so this is the single active visual layer. */
:root{--rog-bg:#101014;--rog-surface:#17171c;--rog-surface2:#202027;--rog-line:rgba(255,255,255,.075);--rog-text:#f4f3f8;--rog-muted:#a6a3ae;--rog-accent:#8b7cf6;--rog-accent2:#b8adff}
html,body,.stApp,[data-testid="stAppViewContainer"]{background:radial-gradient(900px 520px at 65% -260px,rgba(116,91,230,.11),transparent 70%),var(--rog-bg)!important}.block-container{max-width:1040px!important;padding:10px 28px 154px!important}
[data-testid="stSidebar"]{background:#17171b!important;border-right:1px solid rgba(255,255,255,.055)!important;min-width:278px!important}[data-testid="stSidebar"]>div:first-child{padding:20px 12px!important}[data-testid="stSidebar"] button{min-height:39px!important;border-radius:9px!important;font-size:13px!important;padding:0 11px!important}[data-testid="stSidebar"] button[kind="primary"]{background:#292733!important;border-color:transparent!important;box-shadow:none!important;color:white!important}[data-testid="stSidebar"] button:hover{background:#232329!important;border-color:transparent!important}.rog-profile{border:0;background:#202025;margin-bottom:20px}.rog-section{font-size:9px;letter-spacing:1px;margin:18px 10px 7px}
.st-key-rog_top_nav{top:0;z-index:100;border:0;border-bottom:1px solid var(--rog-line);border-radius:0;background:rgba(16,16,20,.88);box-shadow:none;margin:0 0 30px;padding:9px 2px;backdrop-filter:blur(22px)}.rog-top-brand{gap:8px}.rog-top-brand .rog-logo,.rog-top-brand .rog-logo svg{width:29px;height:29px}.rog-top-brand strong{font-size:13px}.rog-top-brand span{font-size:7px}.rog-top-context{display:flex;align-items:center;justify-content:center;gap:9px;font-size:9px}.rog-top-context strong{font-size:13px;margin:0}.rog-profile-context{color:#777580}.rog-inline-status{display:inline-flex;align-items:center;gap:5px;color:#7ed6ba}.rog-inline-status i{width:6px;height:6px;border-radius:50%;background:#55d6ad}.rog-inline-status.is-busy{color:#c1b8ff}.rog-inline-status.is-busy i{background:#9888ff;animation:rog-pulse 1.1s infinite}.st-key-rog_top_nav button{border-radius:10px!important;background:transparent!important;border-color:var(--rog-line)!important}
.rog-welcome-copy{min-height:270px;padding:22px 8px}.rog-welcome-copy h2{font-size:clamp(34px,4.4vw,52px);font-weight:650;letter-spacing:-2.1px}.rog-welcome-copy p{font-size:14px;line-height:1.65}.st-key-rog_welcome_art{min-height:270px;border:0;background:radial-gradient(circle,rgba(104,77,230,.15),transparent 64%)}
[data-testid="stChatMessage"]{max-width:820px;margin:0 auto 25px!important;gap:14px!important;align-items:flex-start}[data-testid="stChatMessageAvatarUser"],[data-testid="stChatMessageAvatarAssistant"]{width:30px!important;height:30px!important;border:1px solid var(--rog-line)!important;background:#24232b!important;color:#c9c1ff!important;border-radius:10px!important;box-shadow:none!important}[data-testid="stChatMessageContent"]{border:0!important;border-radius:0!important;padding:1px 4px!important;background:transparent!important;font-size:15px;line-height:1.72;color:#eae9ee}[data-testid="stChatMessageContent"] h1{font-size:27px;line-height:1.22;letter-spacing:-.65px;margin:12px 0 18px}[data-testid="stChatMessageContent"] h2{font-size:21px;letter-spacing:-.35px;margin:22px 0 10px}[data-testid="stChatMessageContent"] h3{font-size:17px;margin:18px 0 8px}[data-testid="stChatMessageContent"] li{margin:.34em 0}[data-testid="stChatMessageContent"] code{background:#28272e;border:1px solid var(--rog-line);border-radius:6px;padding:2px 5px}[data-testid="stChatMessageContent"] pre{background:#19191e;border:1px solid var(--rog-line);border-radius:14px;padding:16px}[data-testid="stChatMessage"]:has([data-testid="stChatMessageAvatarUser"]){justify-content:flex-end}[data-testid="stChatMessage"]:has([data-testid="stChatMessageAvatarUser"]) [data-testid="stChatMessageContent"]{background:#27262e!important;border:0!important;border-radius:20px!important;padding:11px 16px!important;max-width:min(76%,680px);margin-left:auto}[data-testid="stChatMessage"]:has([data-testid="stChatMessageAvatarUser"]) [data-testid="stChatMessageAvatarUser"]{order:2;background:#302d42!important}[data-testid="stChatMessageContent"] [data-testid="stCaptionContainer"]{color:#85818f!important;text-transform:none;letter-spacing:.15px;font-size:11px!important}
[data-testid="stBottom"]{background:linear-gradient(180deg,transparent 0%,var(--rog-bg) 30%)!important;padding:32px 18px 18px!important}[data-testid="stBottom"]>div{max-width:860px!important;margin:0 auto!important}[data-testid="stChatInput"]{min-height:62px!important;border:1px solid rgba(255,255,255,.10)!important;border-radius:22px!important;background:#24242b!important;box-shadow:0 14px 42px rgba(0,0,0,.28)!important}[data-testid="stChatInput"]:focus-within{border-color:rgba(164,147,255,.55)!important;box-shadow:0 14px 42px rgba(0,0,0,.3),0 0 0 3px rgba(138,104,255,.09)!important}[data-testid="stChatInput"] textarea{font-size:14px!important}[data-testid="stChatInput"] button{border-radius:12px!important;background:#8b7cf6!important;color:white!important}
.rog-quick-label{margin:14px 0 5px}.stButton>button{border-radius:12px!important;background:#1c1c22!important;border-color:var(--rog-line)!important;color:#d8d6df!important}.stButton>button:hover{background:#25242d!important;border-color:rgba(157,143,242,.34)!important}.stButton>button[kind="primary"]{background:#6f61db!important;border-color:#8173e7!important}
@media(max-width:760px){.block-container{padding:7px 10px 132px!important}.st-key-rog_top_nav{margin-bottom:18px}.rog-top-brand span,.rog-profile-context{display:none}.rog-top-context{justify-content:flex-end}.rog-inline-status{font-size:0}.rog-inline-status i{width:7px;height:7px}.rog-welcome-copy{min-height:auto;padding:12px 8px;text-align:left}.rog-welcome-copy h2{font-size:36px}.rog-welcome-copy p{text-align:left}.st-key-rog_welcome_art{min-height:210px}[data-testid="stChatMessage"]{margin-bottom:21px!important;gap:9px!important}[data-testid="stChatMessageAvatarUser"],[data-testid="stChatMessageAvatarAssistant"]{width:26px!important;height:26px!important}[data-testid="stChatMessageContent"]{font-size:14px;line-height:1.65;padding:0 2px!important}[data-testid="stChatMessage"]:has([data-testid="stChatMessageAvatarUser"]) [data-testid="stChatMessageContent"]{max-width:84%;padding:10px 13px!important;border-radius:17px!important}[data-testid="stBottom"]{padding-left:8px!important;padding-right:8px!important}[data-testid="stChatInput"]{border-radius:19px!important}}
.block-container{padding-top:86px!important}.st-key-rog_top_nav{position:fixed!important;top:8px!important;left:50%!important;transform:translateX(-50%)!important;width:min(960px,calc(100vw - 36px))!important;z-index:100!important;border:1px solid var(--rog-line)!important;border-radius:14px!important;background:rgba(20,20,25,.9)!important;box-shadow:0 10px 36px rgba(0,0,0,.22)!important;margin:0!important;padding:7px 10px!important}@media(max-width:760px){.block-container{padding-top:73px!important}.st-key-rog_top_nav{top:6px!important;width:calc(100vw - 14px)!important;padding:6px 8px!important}[data-testid="stSidebarCollapsed"],[data-testid="stSidebarCollapsedControl"]{display:none!important}}
@media(max-width:760px){.block-container{padding-top:116px!important}}
.st-key-rog_top_nav{position:sticky!important;top:8px!important;left:auto!important;transform:none!important;width:100%!important}.st-key-rog_top_nav .stButton>button{min-height:38px!important;background:transparent!important}.st-key-rog_top_menu_panel{max-width:620px;margin:0 auto 28px;padding:18px;border:1px solid var(--rog-line);border-radius:18px;background:rgba(28,28,34,.98);box-shadow:0 24px 70px rgba(0,0,0,.4)}.st-key-rog_top_menu_panel [data-testid="stMarkdownContainer"] p{margin:0}.st-key-rog_top_menu_panel hr{margin:10px 0}@media(max-width:760px){.st-key-rog_top_nav{top:6px!important;width:100%!important}.st-key-rog_top_menu_panel{margin:0 0 20px;padding:13px;border-radius:15px}}
/* Navigation shell v13: sidebar-first, calm and chat-focused. */
.block-container{max-width:980px!important;padding-top:18px!important}.st-key-rog_top_nav{top:8px!important;margin:0 auto 30px!important;padding:7px 10px!important;border-radius:13px!important;background:rgba(22,22,27,.86)!important;box-shadow:0 8px 28px rgba(0,0,0,.18)!important}.rog-top-context{justify-content:flex-start!important;text-align:left!important}.rog-top-context strong{font-size:14px!important}.st-key-rog_top_nav .stButton>button{justify-content:center!important;border-color:var(--rog-line)!important;color:#d9d5e5!important}.st-key-rog_top_menu_panel{display:none!important}
@media(min-width:761px){[data-testid="stSidebar"]{display:block!important;transform:none!important;visibility:visible!important;min-width:286px!important;max-width:286px!important}[data-testid="stSidebarCollapseButton"],[data-testid="stSidebarCollapsed"],[data-testid="stSidebarCollapsedControl"]{display:none!important}.stApp [data-testid="stAppViewContainer"]>.main{margin-left:0!important}}
@media(max-width:760px){.block-container{padding-top:8px!important}.st-key-rog_top_nav{top:6px!important;margin-bottom:18px!important}.rog-profile-context{display:none!important}[data-testid="stSidebarCollapsed"],[data-testid="stSidebarCollapsedControl"]{display:block!important;visibility:visible!important;opacity:1!important}.rog-welcome-copy h2{font-size:32px!important;letter-spacing:-1.3px!important}}
</style>''', unsafe_allow_html=True)


def render_brand() -> None:
    st.markdown(f'<div class="rog-brand"><div class="rog-logo">{MARK_SVG}</div><div><div class="rog-brand-title">ROG AI</div><div class="rog-brand-sub">FAMILY INTELLIGENCE</div></div></div>', unsafe_allow_html=True)


def render_profile(profile: str) -> None:
    label = PROFILE_LABELS.get(str(profile or "").lower(), str(profile or "").title())
    st.markdown(f'<div class="rog-profile"><div class="rog-profile-line"><div class="rog-avatar" aria-hidden="true">{html.escape(label[:1].upper() or "?")}</div><div><strong>{html.escape(label)}</strong><span>● Workspace privado</span></div></div></div>', unsafe_allow_html=True)


def render_section(text: str) -> None:
    st.markdown(f'<div class="rog-section">{html.escape(text)}</div>', unsafe_allow_html=True)


def render_agent_header(agent_id: str, *, busy: bool = False) -> None:
    icon, name, desc = AGENT_META.get(agent_id, AGENT_META["orchestrator"])
    status, state_class = ("Processando", " is-busy") if busy else ("Pronto", "")
    st.markdown(f'<div class="rog-hero"><div class="rog-hero-row"><div class="rog-agent-icon" aria-hidden="true">{html.escape(icon)}</div><div><div class="rog-agent-name">{html.escape(name)}</div><div class="rog-agent-desc">{html.escape(desc)}</div></div><div class="rog-status{state_class}" role="status"><span class="rog-status-dot"></span><span>{status}</span></div></div></div>', unsafe_allow_html=True)


def render_welcome(agent_id: str, profile: str) -> None:
    _, name, _ = AGENT_META.get(agent_id, AGENT_META["orchestrator"])
    person = PROFILE_LABELS.get(str(profile or "").lower(), str(profile or "").title())
    copy, art = st.columns([1.08, .92], gap="large", vertical_alignment="center")
    with copy:
        st.markdown(f'<section class="rog-welcome-copy"><div class="rog-eyebrow">{html.escape(name)}</div><h2>O que vamos<br>criar, {html.escape(person)}?</h2><p>Converse, pesquise, planeje e trabalhe com seus documentos em um workspace privado para cada perfil.</p></section>', unsafe_allow_html=True)
    with art:
        with st.container(key="rog_welcome_art"):
            st.image(Path(__file__).resolve().parents[1] / "assets" / "rog-ai-core.webp", width="stretch")
