create table if not exists public.rog_user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  profile text not null unique check (lower(profile) in ('allan','beatriz','natan','tainan')),
  role text not null default 'member' check (role in ('member','admin')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.rog_user_profiles enable row level security;
alter table public.rog_user_profiles force row level security;
revoke all on table public.rog_user_profiles from public, anon, authenticated;
grant select, insert, update, delete on table public.rog_user_profiles to service_role;
create index if not exists rog_user_profiles_active_idx on public.rog_user_profiles (active) where active = true;

create table if not exists public.rog_api_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  profile text not null,
  request_id text not null unique,
  agent_id text not null,
  provider text,
  model text,
  success boolean not null,
  duration_ms integer,
  input_tokens integer,
  output_tokens integer,
  estimated_cost numeric(12,6),
  error_type text,
  created_at timestamptz not null default now()
);

alter table public.rog_api_usage enable row level security;
alter table public.rog_api_usage force row level security;
revoke all on table public.rog_api_usage from public, anon, authenticated;
grant select, insert, update, delete on table public.rog_api_usage to service_role;
create index if not exists rog_api_usage_user_time_idx on public.rog_api_usage (user_id, created_at desc);
create index if not exists rog_api_usage_profile_time_idx on public.rog_api_usage (profile, created_at desc);

create table if not exists public.rog_audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  profile text,
  event_type text not null,
  outcome text not null check (outcome in ('success','failure','denied')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.rog_audit_events enable row level security;
alter table public.rog_audit_events force row level security;
revoke all on table public.rog_audit_events from public, anon, authenticated;
grant select, insert, delete on table public.rog_audit_events to service_role;
create index if not exists rog_audit_events_time_idx on public.rog_audit_events (created_at desc);
create index if not exists rog_audit_events_profile_time_idx on public.rog_audit_events (profile, created_at desc);
